#!/bin/sh /etc/rc.common
# Copyright (C) 2025 Daniel Bauer <mail@david-bauer.net>

START=99
USE_PROCD=1

NAME=dnrsd
PROG=/usr/bin/dnrsd

. /lib/functions.sh

reload_service() {
	start
	# ToDo: Load the configuration
}

service_started() {
	# ToDo: Load the configuration
}

start_service()
{
	ENABLED="$(uci -q get dnrsd.main.enabled)"

	[ "$ENABLED" -gt 0 ] || return

	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance
}
